/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelilusion.vistas;

import hotelilusion.modelo.Conexion;
import hotelilusion.modelo.Habitacion;
import hotelilusion.modelo.HabitacionData;
import hotelilusion.modelo.Huesped;
import hotelilusion.modelo.HuespedData;
import hotelilusion.modelo.Tipo_habitacion;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agus
 */
public class frmhabitacion extends javax.swing.JInternalFrame {
    
    private Conexion con;
    private HabitacionData habitacionData;
    DefaultTableModel model=new DefaultTableModel();
   
    
    

    /**
     * Creates new form frmhabitacion
     */
    public frmhabitacion() {
        initComponents();
                
        String url = "jdbc:mysql://localhost/hotelilusion";
        String usuario = "root";
        String password = "";
        try {
            con=new Conexion(url,usuario,password);
            habitacionData=new HabitacionData(con);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmhuesped.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String accion ="guardar";
    
    void ocultar_columnas() {
        tabladatos.getColumnModel().getColumn(0).setMaxWidth(0);
        tabladatos.getColumnModel().getColumn(0).setMinWidth(0);
        tabladatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    }
    
    void inhabilitar() {
        
        txtid_habitacion.setVisible(false);
        txtnumero.setVisible(false);
        jComboBoxpiso.setVisible(false);
        jEditorPanecaract.setVisible(false);
        txtcantpersonas.setVisible(false);
        txtcantcamas.setVisible(false);
        txtprecio_diario.setVisible(false);
        txtid_tipohab.setVisible(false);
        jComboBoxestado.setVisible(false);
        
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtid_habitacion.setText("");
        txtprecio_diario.setText("");
        jEditorPanecaract.setText("");
        txtid_tipohab.setText("");
    }
    
    
    void habilitar() {
        
        txtid_habitacion.setVisible(false);
        
        txtnumero.setVisible(true);
        jComboBoxpiso.setVisible(true);
        jEditorPanecaract.setVisible(true);
        txtcantpersonas.setVisible(true);
        txtcantcamas.setVisible(true);
        txtprecio_diario.setVisible(true);
        
        txtid_tipohab.setVisible(false);
        
        jComboBoxestado.setVisible(true);
        
        btnguardar.setEnabled(true);
        btneliminar.setEnabled(true);
        btncancelar.setEnabled(true);
        txtid_habitacion.setText("");
        txtprecio_diario.setText("");
        jEditorPanecaract.setText("");
        txtid_tipohab.setText("");
    }
    
    void mostrar (String buscar) {
        try {
            DefaultTableModel modelo;
            Habitacion func = new Habitacion();
            modelo = func.mostrar(buscar);
            tabladatos.setModel(modelo);
            ocultar_columnas();
            jLabeltotalregistros.setText("Total registros " + Integer.toString(func.totalregistros));
            
        }   catch (Exception e) {
        JOptionPane.showConfirmDialog(rootPane, e);
        
        
        
        }
        int numero=Integer.parseInt(txtnumero.getText());
        int piso=Integer.parseInt(jComboBoxpiso.getItemAt(0));
        String caracteristicas=(jEditorPanecaract.getText());
        int cant_personas=Integer.parseInt(txtcantpersonas.getText());
        int cant_camas=Integer.parseInt(txtcantcamas.getText());
        double precio_diario=Double.parseDouble(txtprecio_diario.getText());
        boolean estado=Boolean.parseBoolean(jComboBoxestado.getItemAt(0));
        
        Habitacion habitacion=new Habitacion(numero, piso, caracteristicas, cant_personas, cant_camas,precio_diario, estado);
        habitacionData.guardarHabitacion(habitacion);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtid_habitacion = new javax.swing.JTextField();
        txtid_tipohab = new javax.swing.JTextField();
        jLabelnumero = new javax.swing.JLabel();
        jLabelpiso = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jComboBoxpiso = new javax.swing.JComboBox<>();
        jLabelcaracteristicas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPanecaract = new javax.swing.JEditorPane();
        jLabelcantpersonas = new javax.swing.JLabel();
        jLabelcat_camas = new javax.swing.JLabel();
        txtcantpersonas = new javax.swing.JTextField();
        txtcantcamas = new javax.swing.JTextField();
        jLabelprecio = new javax.swing.JLabel();
        txtprecio_diario = new javax.swing.JTextField();
        jLabelestado = new javax.swing.JLabel();
        jComboBoxestado = new javax.swing.JComboBox<>();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelbuscar = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabeltotalregistros = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de habitaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        txtid_habitacion.setEditable(false);
        txtid_habitacion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtid_habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_habitacionActionPerformed(evt);
            }
        });

        txtid_tipohab.setEditable(false);
        txtid_tipohab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        jLabelnumero.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelnumero.setText("Número");

        jLabelpiso.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelpiso.setText("Piso");

        txtnumero.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });

        jComboBoxpiso.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jComboBoxpiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Piso01", "Piso02", "Piso03", "Piso04", "Piso05", "Piso06", "Piso07", "Piso08", "Piso09", "Piso10" }));
        jComboBoxpiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpisoActionPerformed(evt);
            }
        });

        jLabelcaracteristicas.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelcaracteristicas.setText("Características");

        jScrollPane1.setViewportView(jEditorPanecaract);

        jLabelcantpersonas.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelcantpersonas.setText("Cantidad de Personas");

        jLabelcat_camas.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelcat_camas.setText("Cantidad de Camas");

        txtcantpersonas.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtcantpersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantpersonasActionPerformed(evt);
            }
        });

        txtcantcamas.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtcantcamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantcamasActionPerformed(evt);
            }
        });

        jLabelprecio.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelprecio.setText("Precio Diario");

        txtprecio_diario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtprecio_diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio_diarioActionPerformed(evt);
            }
        });

        jLabelestado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelestado.setText("Estado");

        jComboBoxestado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jComboBoxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "1", "2", "3", " " }));
        jComboBoxestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxestadoActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(0, 51, 255));
        btnnuevo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(0, 51, 255));
        btnguardar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(0, 51, 255));
        btncancelar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtid_tipohab, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtid_habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelnumero)
                                        .addComponent(jLabelpiso)
                                        .addComponent(jLabelcaracteristicas)
                                        .addComponent(jLabelcat_camas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelcantpersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelestado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxpiso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnumero)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtcantpersonas)
                                    .addComponent(txtcantcamas)
                                    .addComponent(txtprecio_diario)
                                    .addComponent(jComboBoxestado, 0, 183, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btncancelar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid_habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid_tipohab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnumero)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelpiso)
                            .addComponent(jComboBoxpiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabelcaracteristicas)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelcantpersonas)
                    .addComponent(txtcantpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelcat_camas)
                    .addComponent(txtcantcamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelprecio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtprecio_diario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelestado)
                    .addComponent(jComboBoxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btncancelar))
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Habitaciones", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabelbuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbuscar.setText("Buscar");

        txtbuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        tabladatos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        btnbuscar.setBackground(new java.awt.Color(0, 51, 255));
        btnbuscar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(0, 51, 255));
        btneliminar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(0, 51, 255));
        btnsalir.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabeltotalregistros.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabeltotalregistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltotalregistros.setText("Registros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnbuscar)
                .addGap(34, 34, 34)
                .addComponent(btneliminar)
                .addGap(18, 18, 18)
                .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbuscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(btneliminar)
                    .addComponent(btnsalir))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabeltotalregistros)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnguardar.setText("Guardar");
        accion="guardar";
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if (txtnumero.getText().length() ==0) {
            JOptionPane.showConfirmDialog(rootPane, "Por favor ingrese un número de habitación");
            txtnumero.requestFocus();
        }
        
        if (txtprecio_diario.getText().length() ==0) {
            JOptionPane.showConfirmDialog(rootPane, "Por favor ingrese el precio diario de la habitación");
            txtprecio_diario.requestFocus();
        }
        
        Habitacion habitacion=new Habitacion();
        Habitacion func = new Habitacion();
        
        habitacion.setNumero(Integer.parseInt(txtnumero.getText()));
        int seleccionado = jComboBoxpiso.getSelectedIndex();
        habitacion.setPiso(Integer.parseInt(jComboBoxpiso.getItemAt(seleccionado)));
        habitacion.setCaracteristicas(jEditorPanecaract.getText());
        habitacion.setCant_personas(Integer.parseInt(txtcantpersonas.getText()));
        habitacion.setCant_de_camas(Integer.parseInt(txtcantcamas.getText()));
        habitacion.setPrecio_diario(Double.parseDouble(txtprecio_diario.getText()));
                
        seleccionado = jComboBoxestado.getSelectedIndex();
        habitacion.setEstado(Boolean.parseBoolean(jComboBoxestado.getToolTipText()));
        
        if (accion.equals("guardar")) {
            if(func.guardarHabitacion(habitacion)) {
                JOptionPane.showMessageDialog(rootPane, "La habitación fue registrada");
                mostrar("");
                inhabilitar();
            } else if (accion.equals("actualizar")) {
                habitacion.getId_habitacion(Integer.parseInt(txtid_habitacion.getText()));
                
        
             if (func.actualizar(habitacion)) {
                 JOptionPane.showMessageDialog(rootPane, "La habitación fue actualizada correctamente");
                mostrar("");
                inhabilitar();
                 
             }
                
                
                
            }
        }
        
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        
        if (!txtid_habitacion.getText().equals("")){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar la habitación", "Confirmar",2);
            
            if(confirmacion ==0) {
                
                Habitacion func = new Habitacion();
                Habitacion habitacion=new Habitacion();
                
                habitacion.setId_habitacion(Integer.parseInt(txtid_habitacion.getText()));
                func.eliminar(habitacion);
                mostrar("");
                inhabilitar();
            }
            
        }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
        txtnumero.transferFocus();
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void jComboBoxpisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpisoActionPerformed
        // TODO add your handling code here:
        jComboBoxpiso.transferFocus();
    }//GEN-LAST:event_jComboBoxpisoActionPerformed

    private void txtcantpersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantpersonasActionPerformed
        // TODO add your handling code here:
        txtcantpersonas.transferFocus();
    }//GEN-LAST:event_txtcantpersonasActionPerformed

    private void txtprecio_diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio_diarioActionPerformed
        // TODO add your handling code here:
        txtprecio_diario.transferFocus();
    }//GEN-LAST:event_txtprecio_diarioActionPerformed

    private void jComboBoxestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxestadoActionPerformed
        // TODO add your handling code here:
        jComboBoxestado.transferFocus();
    }//GEN-LAST:event_jComboBoxestadoActionPerformed

    private void txtcantcamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantcamasActionPerformed
        // TODO add your handling code here:
        txtcantcamas.transferFocus();
    }//GEN-LAST:event_txtcantcamasActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        // TODO add your handling code here:
        btnguardar.setText("Editar");
        habilitar();
        btneliminar.setEnabled(true);
        accion="editar";
        
        int fila = tabladatos.rowAtPoint(evt.getPoint());
        txtid_habitacion.setText(tabladatos.getValueAt(fila, 0).toString());
        txtnumero.setText(tabladatos.getValueAt(fila, 1).toString());
        jComboBoxpiso.setSelectedItem(tabladatos.getValueAt(fila,3).toString());
        jEditorPanecaract.setText(tabladatos.getValueAt(fila, 4).toString());
        txtcantpersonas.setText(tabladatos.getValueAt(fila, 5).toString());
        txtcantcamas.setText(tabladatos.getValueAt(fila, 6).toString());
        txtprecio_diario.setText(tabladatos.getValueAt(fila, 7).toString());
        txtid_tipohab.setText(tabladatos.getValueAt(fila, 8).toString());
        jComboBoxestado.setSelectedItem(tabladatos.getValueAt(fila, 9).toString());
        
    }//GEN-LAST:event_tabladatosMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtid_habitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_habitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_habitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmhabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmhabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmhabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmhabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmhabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> jComboBoxestado;
    private javax.swing.JComboBox<String> jComboBoxpiso;
    private javax.swing.JEditorPane jEditorPanecaract;
    private javax.swing.JLabel jLabelbuscar;
    private javax.swing.JLabel jLabelcantpersonas;
    private javax.swing.JLabel jLabelcaracteristicas;
    private javax.swing.JLabel jLabelcat_camas;
    private javax.swing.JLabel jLabelestado;
    private javax.swing.JLabel jLabelnumero;
    private javax.swing.JLabel jLabelpiso;
    private javax.swing.JLabel jLabelprecio;
    private javax.swing.JLabel jLabeltotalregistros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantcamas;
    private javax.swing.JTextField txtcantpersonas;
    private javax.swing.JTextField txtid_habitacion;
    private javax.swing.JTextField txtid_tipohab;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtprecio_diario;
    // End of variables declaration//GEN-END:variables
}
