/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelilusion.vistas;

import sun.security.util.Password;

/**
 *
 * @author agus
 */
public class frmacceso extends javax.swing.JFrame {

    private Object txtusuario;

    /**
     * Creates new form frmprincipal
     */
    public frmacceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txthotel = new javax.swing.JTextPane();
        jlgusuario = new javax.swing.JLabel();
        jlbcontraseña = new javax.swing.JLabel();
        txtdatousuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jbtnentrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txthotel.setBackground(new java.awt.Color(102, 255, 204));
        txthotel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txthotel.setFont(new java.awt.Font("Vineta BT", 2, 36)); // NOI18N
        txthotel.setForeground(new java.awt.Color(255, 0, 51));
        txthotel.setText("Hotel Ilusión");
        jScrollPane1.setViewportView(txthotel);

        jlgusuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jlgusuario.setText("Usuario");
        jlgusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jlbcontraseña.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jlbcontraseña.setText("Contraseña");
        jlbcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        txtdatousuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtdatousuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPassword.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jbtnentrar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbtnentrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\agus\\Desktop\\mama\\opciones\\SistemaReservaHotel\\src\\files\\nuevo.GIF")); // NOI18N
        jbtnentrar.setText("Entrar");
        jbtnentrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jbtnentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnentrarMouseClicked(evt);
            }
        });
        jbtnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnentrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jlgusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdatousuario)
                                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlgusuario)
                    .addComponent(txtdatousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbcontraseña)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jbtnentrar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnentrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnentrarMouseClicked
        String usuario="administrador";
        String contraseña="1234";
        
        String Password = null;
        
        
        
    }//GEN-LAST:event_jbtnentrarMouseClicked

    private void jbtnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnentrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmacceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmacceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmacceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmacceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmacceso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnentrar;
    private javax.swing.JLabel jlbcontraseña;
    private javax.swing.JLabel jlgusuario;
    private javax.swing.JTextField txtdatousuario;
    private javax.swing.JTextPane txthotel;
    // End of variables declaration//GEN-END:variables
}
